train_config:
  train_type: "ES"
  env_name: "CartPole-v1"
  num_generations: 500
  evaluate_every_gen: 10

  es_name: "OpenES"
  es_config:
    popsize: 100
    opt_name: "adam"
  es_params:
    lrate_init: 0.04
    lrate_decay: 0.999
    lrate_limit: 0.001
    sigma_init: 0.03
    sigma_decay: 0.999
    sigma_limit: 0.01
    init_min: -0.1
    init_max: 0.1

  fitness_config:
    maximize: true
    centered_rank: true
    z_score: false
    w_decay: 0.0
  
  problem_train_config:
    num_env_steps: 200
    num_rollouts: 20
  problem_test_config:
    num_env_steps: 200
    num_rollouts: 164

  network_name: "MLP"
  network_config: 
    num_hidden_units: 64
    num_hidden_layers: 2
    hidden_activation: "relu"
    output_activation: "categorical"

log_config:
  time_to_track: ["imp_iter"]
  what_to_track: ["sparsity", "best_perf", "final_perf"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"

device_config:
  num_devices: 1
  device_type: "gpu"