train_config:
  train_type: "ES"
  num_generations: 2500
  evaluate_every_gen: 10

  env_name: "Breakout-MinAtar"
  env_kwargs: {}
  env_params: {}
  num_test_rollouts: 164
  num_train_rollouts: 64

  es_name: "OpenES"
  es_config:
    popsize: 256
    opt_name: "adam"
  es_params:
    lrate_init: 0.05
    lrate_decay: 0.999
    lrate_limit: 0.001
    sigma_init: 0.2
    sigma_decay: 0.999
    sigma_limit: 0.001

  fitness_config:
    maximize: true
    centered_rank: true
    z_score: true
    w_decay: 0.01

  network_name: "MLP"
  network_config: 
    num_hidden_layers: 2
    num_hidden_units: 128
    hidden_activation: "relu"
    output_activation: "categorical"

log_config:
  time_to_track: ["num_steps"]
  what_to_track: ["return"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    name: breakout-open-es-mlp-z

device_config:
  num_devices: 1
  device_type: "gpu"